# Generated by Django 5.1.7 on 2025-03-08 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
