# Generated by Django 5.1.7 on 2025-03-10 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_notehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
