# Generated by Django 5.1.7 on 2025-03-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='notes.note'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], max_length=20),
        ),
    ]
